apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: rpa-tekton-prove-concept-claim
spec:
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
  resources:
    requests:
      storage: 1Gi