apiVersion: tekton.dev/v1alpha1
kind: PipelineRun
metadata:
  generateName: rpa-tekton-prove-concept-pipeline-run
spec:
  params:
    - name: uid
      value: $(context.pipelineRun.uid)
    - name: GIT_REPO
      value: https://github.com/greg2018/RpaTektonProveConcept.git
    - name: GIT_REVISION
      value: BR01-TRY-OUT-Tekton-Pipeline
    
      
  pipelineRef:
    name: rpa-tekton-prove-concept-pipeline
  workspaces:
    - name: rpaTektonProveConceptWorkspace
      persistentVolumeClaim:
        claimName: rpa-tekton-prove-concept-claim
    - name: output
      persistentVolumeClaim:
        claimName: rpa-tekton-prove-concept-claim
    - name: source
      persistentVolumeClaim:
        claimName: rpa-tekton-prove-concept-claim