apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: show-readme
  description: Read and display README file.
spec:
  workspaces:
  - name: source
  steps:
  - name: read
    image: alpine:latest
    script: | 
      #!/usr/bin/env sh
      echo "++++++before cd .."
      pwd
      ls -l
      echo "++++++after cd workspace"
      cd workspace/source
      pwd
      ls -l
      echo $(workspaces.source.path)
      cat $(workspaces.source.path)/README.md