apiVersion: v1
kind: Secret
metadata:
  name: rpaorchestrator-env-secret
  namespace: adam
data: 
  ORCHESTRATOR_DATASOURCE_PASSWORD: Z2hJZGtJNTFWdEVr
  RABBITMQ_PASSWORD: Z3Vlc3Q=
  ORCHESTRATOR_CAMUNDA_PASSWORD: ZGVtbw==